### ISSUE TITLE
Replacing of numbers not working

### ISSUE THREAD

**Issue by spyro2000** [stephenharris/py_obfuscate#2]
Hi there!

`I tried to replace numbers with random data by defining something like

```yaml
my-table:
  my-column:
    type: integer
    min: 0
    max: 10
```` 

This did not work:

```
index = random.randint(0, len(values) - 1)
TypeError: object of type 'int' has no len()
`````

Seems like the script doesn't work for numbers, only for strings?
